name: Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm i

      - name: Generate Release Note
        run: npx changelogithub --output GEN_CHANGELOG.md

      - name: Generate Chrome Extension
        run: npm run build:prepare && npm run build && npm run pack:crx
        env:
          WEBEXT_PRIVATE_KEY: ${{ secrets.WEBEXT_PRIVATE_KEY }}

      - uses: softprops/action-gh-release@v2
        with:
          body_path: GEN_CHANGELOG.md
          files: |
            webext-gesture.crx
